services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: db_root_password
      MYSQL_DATABASE: opdevlucht_db
      MYSQL_USER: opdevlucht
      MYSQL_PASSWORD: db_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - internal
    dns:
      - 192.168.1.141

  deno-app:
    build: .
    ports:
      - "4500:4500"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: opdevlucht
      DB_PASSWORD: db_password
      DB_NAME: opdevlucht_db
    networks:
      - internal
    dns:
      - 192.168.1.141

  adminer:
    image: adminer
    restart: always
    ports:
      - 4501:8080
    networks:
      - internal
    dns:
      - 192.168.1.141
volumes:
  db_data:

networks:
  internal:
    driver: bridge
