services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: example_password
      MYSQL_DATABASE: example_db
      MYSQL_USER: example_user
      MYSQL_PASSWORD: example_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  deno-app:
    build: .
    ports:
      - "4500:4500"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: example_user
      DB_PASSWORD: example_password
      DB_NAME: example_db

volumes:
  db_data:
