services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: db_root_password
      MYSQL_DATABASE: opdevlucht_db
      MYSQL_USER: opdevlucht
      MYSQL_PASSWORD: db_password
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d
    networks:
      - internal
    dns:
      - 192.168.1.141

  deno-app:
    build: .
    ports:
      - "4500:4500"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: opdevlucht
      DB_PASSWORD: db_password
      DB_NAME: opdevlucht_db
    networks:
      - internal
    dns:
      - 192.168.1.141

  phpmyadmin:
    image: arm64v8/phpmyadmin
    restart: always
    ports:
      - 4501:80
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: opdevlucht
      PMA_PASSWORD: db_password
    depends_on:
      - db
    networks:
      - internal
    dns:
      - 192.168.1.141

networks:
  internal:
    driver: bridge
