version: "3.8"

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: example_password
      MYSQL_DATABASE: example_db
      MYSQL_USER: example_user
      MYSQL_PASSWORD: example_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - internal

  deno-app:
    build: .
    ports:
      - "4500:4500"  # Expose your API to host
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: example_user
      DB_PASSWORD: example_password
      DB_NAME: example_db
    networks:
      - internal

volumes:
  db_data:

networks:
  internal:
    driver: bridge
